### ISSUE TITLE
Scoresheet goes blank when IPad rotates

### ISSUE THREAD

**Issue by Hazzer890** [CJBuchel/TMS#171]
### Describe the bug

Scoresheet goes blank on IPad when the screen is rotated, seems that it doesn't retrieve the scoresheet from the local db or from the server. Unless you go out and then back in to the ref scoring where it will get it back from the local db.

Issue is intermittent

### Steps to reproduce

.

### Logs

```shell
.
```

### Expected behavior

should rescale the missions and not need to retrieve the data when the ipad rotates.

### OS

iOS IPad

### Additional context

ur cute

**Comment by CJBuchel** [comment]
![20241102_114705.jpg](https://github.com/user-attachments/assets/68791652-b4ab-41ea-9cd8-e65859764e4d)

**Comment by CJBuchel** [comment]
Might have been resolved in 2024.1.1 with patch that wraps the scoring display in the `WithNextScoring` widget
